### PR TITLE
Fixed Two Typos in faq.md

### PR DESCRIPTION
**Pull request by conorstew**

### CODE REVIEW

**Comment by 4s3ti** [comment]
don't worry about the tests failing .. ill check your PR as soon as i have a bit ...

**Comment by 4s3ti** [comment]
Change the branch to test please

**Comment by conorstew** [comment]
Oops, should be good now :)

**Comment by 4s3ti** [comment]
Thanks a lot for your contribution and I am Sorry for taking some time to take a look a this! 

This has been now deployed.

**Pull request merged**
