### PR TITLE
add persistentkeepalive info

### PR DESCRIPTION
**Pull request by DerDanilo**
https://github.com/pivpn/pivpn/pull/1321#pullrequestreview-677526289

### CODE REVIEW

**Comment by 4s3ti** [comment]
Crap I messed up here ... I am really sorry! 

Can you please close this one and re-open another one with the updated master?? 

either that or Revert my "Not so conflict resolving commit" and properly fix the conflict

`## Updatinging Wireguard`

Should be

`## Updating Wireguard`

**Comment by DerDanilo** [comment]
Happens. Just merge it and commit a change later on. Or the owner of the repo can do a commit into the master. Shouldn't be an issue for a docs repo.

**Comment by orazioedoardo** [comment]
> Happens. Just merge it and commit a change later on. Or the owner (you?) of the repo can do a commit into the master. Shouldn't be an issue for a docs repo.

You can just add more commits to your branch.

> Keep Wireguard connected / Connection issues / PersistentKeepalive.

It's not actually related to connection issues. Yes it will speed up connections a bit since there is no on-demand handshake but, in the context of PiVPN, persistentkeepalive is only useful if the raspberrypi wants to connect to a client long after the client initiated session has expired due to nat.

> You may update already existing profiles with `pivpn -up` ("Updates PiVPN Scripts").

This is not available anymore.

**Comment by DerDanilo** [comment]
> > You may update already existing profiles with `pivpn -up` ("Updates PiVPN Scripts").
> 
> This is not available anymore.

I removed the line from the manual.
I think that it's necessary to be able to regenerate the profiles in case of config changes. Was there ever a function to do so?
Right now I'm handling this with Ansible which, or course, requires Ansible skills but would be nice if the script(s) itself would be able to handle this.

**Comment by orazioedoardo** [comment]
> I think that it's necessary to be able to regenerate the profiles in case of config changes. Was there ever a function to do so?

No, however this could be a feature of `pivpn add`: detect when the template (setupvars) has been changed and prompt for regeneration.

**Comment by 4s3ti** [comment]
will merge this when test gets merged into master.

**Pull request merged**
